const mangaList = [
  {
    id: 1,
    img: "./img.jpg",
    title: "Gener test",
    tags: ["Драма", "Бойовик"],
    views: "3000",
    release: "12.12.2022",
    rating: 4.8,
    images: [
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
    ],
  },
  {
    id: 2,
    img: "./img2.jpg",
    title: "Gener test",
    tags: ["Драма", "Бойовик"],
    views: "3000",
    release: "12.12.2022",
    rating: 4.8,
    images: [
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
    ],
  },
  {
    id: 3,
    img: "./img3.jpg",
    title: "No Game, No Life",
    tags: ["Драма", "Бойовик"],
    views: "3000",
    release: "12.12.2022",
    rating: 4.8,
    images: [
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
    ],
  },
  {
    id: 4,
    img: "./img4.jpg",
    title: "Gener test",
    tags: ["Драма", "Бойовик"],
    views: "3000",
    release: "12.12.2022",
    rating: 4.8,
    images: [
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
    ],
  },
  {
    id: 5,
    img: "./img3.jpg",
    title: "Моя геройська академія",
    tags: ["Драма", "Бойовик"],
    views: "3000",
    release: "12.12.2022",
    rating: 4.8,
    images: [
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
    ],
  },
  {
    id: 6,
    img: "./img2.jpg",
    title: "Людина-бензопила, що робить бз-бз-бз та інші типові довгі назви на японській",
    tags: ["Драма", "Бойовик"],
    views: "3000",
    release: "12.12.2022",
    rating: 4.8,
    images: [
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
    ],
  },
  {
    id: 7,
    img: "./img.jpg",
    title: "Gener test",
    tags: ["Драма", "Бойовик"],
    views: "3000",
    release: "12.12.2022",
    rating: 4.8,
    images: [
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
    ],
  },
  {
    id: 8,
    img: "./img4.jpg",
    title: "Gener test",
    tags: ["Драма", "Бойовик"],
    views: "3000",
    release: "12.12.2022",
    rating: 4.8,
    images: [
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
      "./img.jpg",
      "./img2.jpg",
      "/img3.jpg",
      "./img4.jpg",
    ],
  },
];
